
file=file_text_open_append("save.sql")
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Indie");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Action");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Adventure");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Casual");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Strategy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Simulation");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"RPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Free to Play");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Singleplayer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Massively Multiplayer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Sports");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Violent");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Racing");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Gore");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Multiplayer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Great Soundtrack");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Atmospheric");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Puzzle");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"2D");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Horror");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Nudity");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Anime");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Story Rich");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Open World");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"VR");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Difficult");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Sci-fi");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Fantasy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Shooter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Co-op");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Female Protagonist");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Funny");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Platformer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"FPS");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"First-Person");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Pixel Graphics");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Utilities");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Sexual Content");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Survival");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Movie");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Comedy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Sandbox");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Design &amp; Illustration");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Arcade");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Family Friendly");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Retro");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Classic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Turn-Based");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Point &amp; Click");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Audio Production");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Third Person");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Zombies");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Online Co-Op");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Visual Novel");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Exploration");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Controller");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Space");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cute");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Psychological Horror");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Education");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Animation &amp; Modeling");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Memes");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Tactical");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Local Multiplayer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Replay Value");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Rogue-like");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Local Co-Op");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Shoot '+"'"+'Em Up");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mystery");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Survival Horror");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Physics");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dark");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Action RPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Walking Simulator");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Realistic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"RPGMaker");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Fast-Paced");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Video Production");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"RTS");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Stealth");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Turn-Based Strategy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Building");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Hidden Object");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Action-Adventure");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"War");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Short");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Crafting");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Historical");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mature");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Puzzle-Platformer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"PvP");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Hack and Slash");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Web Publishing");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Side Scroller");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Third-Person Shooter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Fighting");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Colorful");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Bullet Hell");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Tower Defense");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Management");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Top-Down");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Illuminati");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Character Customization");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Relaxing");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Post-apocalyptic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Music");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Moddable");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dating Sim");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"JRPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Competitive");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"MMORPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dark Fantasy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Drama");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Episodic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Software Training");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Choices Matter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"4 Player Local");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Medieval");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"World War II");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Futuristic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Software");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dungeon Crawler");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Beat '+"'"+'em up");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Rogue-lite");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Party-Based RPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Procedural Generation");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Robots");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Team-Based");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cyberpunk");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Romance");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Isometric");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Thriller");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Military");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Magic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Crime");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Surreal");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Minimalist");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Parkour");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Base Building");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Card Game");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Choose Your Own Adventure");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Top-Down Shooter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Metroidvania");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Aliens");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Turn-Based Combat");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Driving");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Perma Death");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"City Builder");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dark Humor");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Board Game");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Twin Stick Shooter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Blood");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"3D Platformer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Level Editor");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Steampunk");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Turn-Based Tactics");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Multiple Endings");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Flight");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cartoony");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"MOBA");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Photo Editing");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Stylized");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Trains");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"3D Vision");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Grand Strategy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Economy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Detective");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Soundtrack");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Destruction");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Kickstarter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Loot");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Game Development");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"1990'+"'"+'s");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Arena Shooter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Experimental");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Documentary");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Resource Management");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dystopian ");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Psychological");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mod");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cult Classic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"PvE");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Demons");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"1980s");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cartoon");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"TrackIR");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Lovecraftian");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Match 3");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Hand-drawn");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"4X");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Remake");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"2.5D");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Interactive Fiction");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"2D Fighter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Touch-Friendly");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Ninja");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Split Screen");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Abstract");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mechs");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Space Sim");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Real-Time with Pause");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dragons");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Real-Time");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dinosaurs");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Rhythm");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Assassin");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Wargame");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Pirates");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"GameMaker");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Strategy RPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Superhero");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Games Workshop");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Linear");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Trading Card Game");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Comic Book");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Tactical RPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Tutorial");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Tanks");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Text-Based");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Alternate History");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Noir");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cold War");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Psychedelic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Otome");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Clicker");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Voxel");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"e-sports");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Hacking");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Western");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dark Comedy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mouse only");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Gun Customization");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Gaming");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Swordplay");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Science");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Supernatural");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"CRPG");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Hex Grid");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Naval");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Co-op Campaign");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Real Time Tactics");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Satire");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Score Attack");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Quick-Time Events");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Hunting");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"God Game");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cinematic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Class-Based");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Heist");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Runner");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Villain Protagonist");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Political");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Politics");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Vampire");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Character Action Game");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Narration");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Football");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Crowdfunded");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Lore-Rich");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"America");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Parody ");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"World War I");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Time Travel");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Based On A Novel");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Trading");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Soccer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Silent Protagonist");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"FMV");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Gothic");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Underwater");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"LEGO");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Grid-Based Movement");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Bullet Time");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Warhammer 40K");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Pinball");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Martial Arts");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Sniper");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mythology");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Asynchronous Multiplayer");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Agriculture");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Programming");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"6DOF");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Conspiracy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Star Wars");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Fishing");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Steam Machine");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Batman");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Time Attack");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Modern");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Spectacle fighter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Time Manipulation");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"On-Rails Shooter");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Philisophical");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Rome");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Offroad");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Nonlinear");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Inventory Management");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mining");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"360 Video");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Sailing");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Werewolves");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Benchmark");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Music-Based Procedural Generation");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Chess");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Gambling");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Hardware");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Horses");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Dynamic Narration");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Diplomacy");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mars");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Typing");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mystery Dungeon");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"NSFW");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Capitalism");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Experience");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Word Game");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Basketball");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Investigation");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Golf");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Feature Film");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Sokoban");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Underground");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Lara Croft");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Lemmings");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Artificial Intelligence");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Transhumanism");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Bowling");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Mini Golf");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Wrestling");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Pool");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Conversation");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Foreign");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Spelling");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Faith");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Intentionally Awkward Controls");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Cycling");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Voice Control");')      file_text_writeln(file)
file_text_write_string(file,'INSERT INTO tag(TagID,Name) VALUES(null,"Bikes");')      file_text_writeln(file)
file_text_close(file)
